"""Service layer helpers for interactive product modules."""

from src.services.channel_idea_service import ChannelIdeaBundle, IdeaSuggestion, ThemeRecommendation, build_grounded_idea_bundle, maybe_generate_ai_overlay
from src.services.channel_insights_service import (
    TOPIC_MODE_BERTOPIC_OPTIONAL,
    TOPIC_MODE_HEURISTIC,
    list_connected_channels,
    load_channel_insights,
    refresh_channel_insights,
)
from src.services.model_artifact_service import (
    MODEL_TYPE_BERTOPIC_GLOBAL,
    ModelArtifactManifest,
    ModelArtifactStatus,
    ensure_bertopic_artifact_ready,
    fetch_bertopic_manifest,
    get_bertopic_artifact_status,
    get_model_artifact_manifest_url,
    model_artifacts_enabled,
)
from src.services.channel_snapshot_store import (
    DEFAULT_CHANNEL_INSIGHTS_DB,
    get_tracked_channel,
    initialize_channel_snapshot_store,
    list_channel_snapshot_history,
    list_tracked_channels,
    load_latest_channel_snapshot,
    store_channel_snapshot,
    upsert_tracked_channel,
)
from src.services.public_channel_service import PublicChannelWorkspace, ensure_public_channel_frame, load_public_channel_workspace
from src.services.google_oauth_service import (
    GOOGLE_OAUTH_SCOPES,
    build_google_authorization_url,
    clear_google_oauth_session,
    complete_google_oauth_callback,
    fetch_google_profile,
    get_google_credentials,
    get_google_oauth_client_config,
    get_google_oauth_redirect_uri,
    get_google_profile,
    oauth_configured,
    oauth_ready_error,
)
from src.services.assistant_knowledge import KnowledgeRecord, get_knowledge_record, get_knowledge_records, get_related_question_titles, load_knowledge_records
from src.services.assistant_service import AssistantReply, answer_question, extract_page_context, starter_prompts_for_page, submit_feedback
from src.services.topic_analysis_service import (
    add_channel_video_features,
    assign_topic_labels,
    build_duration_metrics,
    build_publish_day_metrics,
    build_publish_hour_metrics,
    build_title_pattern_metrics,
    build_topic_metrics,
    classify_title_pattern,
    duration_bucket,
    normalize_topic_token,
    tokenize_topic_text,
)
from src.services.topic_model_runtime import TopicModelInferenceResult, apply_optional_topic_model, build_bertopic_inference_text
from src.services.cache_service import CachedAnswerRecord, fetch_exact_cached_answer, initialize_cache_db, list_cached_answers_for_scope, store_answer
from src.services.outlier_ai import InsightCard, OutlierAIReport, generate_outlier_ai_report
from src.services.outliers_finder import (
    ChannelBaseline,
    DURATION_BUCKETS,
    OutlierCandidate,
    OutlierSearchRequest,
    OutlierSearchResult,
    build_age_bucket_summary,
    build_duration_summary,
    build_scan_quality_summary,
    build_title_keyword_summary,
    build_title_pattern_summary,
    search_outlier_videos,
    score_band_for_value,
)
from src.services.retrieval_service import CachedAnswerMatch, KnowledgeMatch, clear_retrieval_caches, search_cached_answers, search_knowledge
from src.services.transcript_service import TranscriptOption, fetch_transcript_text, list_transcript_options, prepare_transcript_download
from src.services.youtube_owner_analytics_service import OwnerAnalyticsBundle, fetch_owner_channel_analytics, list_owned_channels
from src.services.youtube_tools import (
    PLAYLIST_PREVIEW_LIMIT_DEFAULT,
    STREAMLIT_DOWNLOAD_LIMIT_BYTES,
    BatchItemResult,
    FormatOption,
    PlaylistPreview,
    PreparedArtifact,
    ResolvedYoutubeTarget,
    VideoMetadata,
    fetch_playlist_entries,
    fetch_playlist_preview,
    fetch_video_metadata,
    ffmpeg_available,
    get_available_formats,
    prepare_audio_download,
    prepare_batch_operation,
    prepare_playlist_operation,
    prepare_thumbnail_download,
    prepare_video_download,
    validate_youtube_url,
)

__all__ = [
    "ChannelIdeaBundle",
    "IdeaSuggestion",
    "ThemeRecommendation",
    "build_grounded_idea_bundle",
    "maybe_generate_ai_overlay",
    "TOPIC_MODE_HEURISTIC",
    "TOPIC_MODE_BERTOPIC_OPTIONAL",
    "list_connected_channels",
    "load_channel_insights",
    "refresh_channel_insights",
    "MODEL_TYPE_BERTOPIC_GLOBAL",
    "ModelArtifactManifest",
    "ModelArtifactStatus",
    "ensure_bertopic_artifact_ready",
    "fetch_bertopic_manifest",
    "get_bertopic_artifact_status",
    "get_model_artifact_manifest_url",
    "model_artifacts_enabled",
    "DEFAULT_CHANNEL_INSIGHTS_DB",
    "get_tracked_channel",
    "initialize_channel_snapshot_store",
    "list_channel_snapshot_history",
    "list_tracked_channels",
    "load_latest_channel_snapshot",
    "store_channel_snapshot",
    "upsert_tracked_channel",
    "PublicChannelWorkspace",
    "ensure_public_channel_frame",
    "load_public_channel_workspace",
    "GOOGLE_OAUTH_SCOPES",
    "build_google_authorization_url",
    "clear_google_oauth_session",
    "complete_google_oauth_callback",
    "fetch_google_profile",
    "get_google_credentials",
    "get_google_oauth_client_config",
    "get_google_oauth_redirect_uri",
    "get_google_profile",
    "oauth_configured",
    "oauth_ready_error",
    "KnowledgeRecord",
    "get_knowledge_record",
    "get_knowledge_records",
    "get_related_question_titles",
    "load_knowledge_records",
    "AssistantReply",
    "answer_question",
    "extract_page_context",
    "starter_prompts_for_page",
    "submit_feedback",
    "CachedAnswerRecord",
    "fetch_exact_cached_answer",
    "initialize_cache_db",
    "list_cached_answers_for_scope",
    "store_answer",
    "InsightCard",
    "OutlierAIReport",
    "generate_outlier_ai_report",
    "ChannelBaseline",
    "DURATION_BUCKETS",
    "OutlierCandidate",
    "OutlierSearchRequest",
    "OutlierSearchResult",
    "build_age_bucket_summary",
    "build_duration_summary",
    "build_scan_quality_summary",
    "build_title_keyword_summary",
    "build_title_pattern_summary",
    "search_outlier_videos",
    "score_band_for_value",
    "CachedAnswerMatch",
    "KnowledgeMatch",
    "clear_retrieval_caches",
    "search_cached_answers",
    "search_knowledge",
    "TranscriptOption",
    "fetch_transcript_text",
    "list_transcript_options",
    "prepare_transcript_download",
    "OwnerAnalyticsBundle",
    "fetch_owner_channel_analytics",
    "list_owned_channels",
    "add_channel_video_features",
    "assign_topic_labels",
    "build_duration_metrics",
    "build_publish_day_metrics",
    "build_publish_hour_metrics",
    "build_title_pattern_metrics",
    "build_topic_metrics",
    "classify_title_pattern",
    "duration_bucket",
    "normalize_topic_token",
    "tokenize_topic_text",
    "TopicModelInferenceResult",
    "apply_optional_topic_model",
    "build_bertopic_inference_text",
    "PLAYLIST_PREVIEW_LIMIT_DEFAULT",
    "STREAMLIT_DOWNLOAD_LIMIT_BYTES",
    "BatchItemResult",
    "FormatOption",
    "PlaylistPreview",
    "PreparedArtifact",
    "ResolvedYoutubeTarget",
    "VideoMetadata",
    "fetch_playlist_entries",
    "fetch_playlist_preview",
    "fetch_video_metadata",
    "ffmpeg_available",
    "get_available_formats",
    "prepare_audio_download",
    "prepare_batch_operation",
    "prepare_playlist_operation",
    "prepare_thumbnail_download",
    "prepare_video_download",
    "validate_youtube_url",
]
